# Generated by Django 5.1.15 on 2026-10-08 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('event_type', models.CharField(choices=[('Symposium', 'Symposium'), ('Workshop', 'Workshop'), ('Hackathon', 'Hackathon'), ('Technical Event', 'Technical Event'), ('Non-Technical Event', 'Non-Technical Event'), ('Seminar', 'Seminar'), ('Cultural Event', 'Cultural Event')], db_index=True, max_length=30)),
                ('date', models.DateField(db_index=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('venue', models.CharField(max_length=200)),
                ('registration_deadline', models.DateTimeField()),
                ('max_participants', models.PositiveIntegerField()),
                ('registration_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('status', models.CharField(choices=[('Upcoming', 'Upcoming'), ('Registration Open', 'Registration Open'), ('Registration Closed', 'Registration Closed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], db_index=True, default='Upcoming', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='EventVolunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_assignments', to='events.event')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('event', 'volunteer'), name='unique_event_volunteer')],
            },
        ),
    ]
