# Generated by Django 5.1.15 on 2026-10-08 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_id', models.CharField(editable=False, max_length=40, unique=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], default='Confirmed', max_length=15)),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_codes/')),
                ('attendance_status', models.CharField(choices=[('Not Checked In', 'Not Checked In'), ('Checked In', 'Checked In')], db_index=True, default='Not Checked In', max_length=20)),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('checked_in_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='check_ins_done', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.event')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-registered_at'],
                'indexes': [models.Index(fields=['event', 'attendance_status'], name='registratio_event_i_9c8ca6_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'event'), name='unique_student_event')],
            },
        ),
    ]
